name: Update README

on:
  push:
    paths: currencies.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3

      - name: Install PyYAML
        run: pip install PyYAML

      - name: Install oyaml
        run: pip install oyaml

      - name: Install prettytable
        run: pip install PrettyTable

      - name: Install Path
        run: pip install Path

      - name: Update README
        run: |
          cat README.md | head -n 10 >> README.new.md
          python yaml_to_table.py >> README.new.md
          cat README.md | tail -n +45 >> README.new.md

        - name: rename README
        run: |
          delete README.md
          rename README.new.md >> README.md

      - name: git push README
        run: |
          git config --global user.email "polinatereschenko16@gmail.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update README"
          git push origin main