name: Update README

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-vertion: 3

      - name: Install dependencies
        run: pip install PyYAML
        run: pip install oyaml
        run: pip install prettytable

      - name: Run Python script
        run: python yaml_to_table.py 

      - name: Update README
        run: |
          sed -i 's/## Supported Currencies/## References/' README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update README"
          git push
