name: Update README

on:
  push:
    paths: currencies.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3

      - name: Install Python dependencies
        run: |
          pip install PyYAML
          pip install oyaml
          pip install PrettyTable
          pip install Path

      - name: Update README
        run: |
          INX1=$(cat README.md | grep -n '# Enum Of Currencies'  | cut -d: -f1)
          INX2=$(cat README.md | grep -n '## Refrences'  | cut -d: -f1)
          cat README.md | head -n $INX1 >> README.new.md
          python yaml_to_table.py >> README.new.md
          cat README.md | tail -n +$INX2 >> README.new.md
          rm README.md
          mv README.new.md README.md

      - name: Git Push README
        run: |
          git config --global user.email "polinatereschenko16@gmail.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update README"
          git push origin main