name: Update README

on:
  push:
    paths: currencies.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-vertion: 3

      - name: Install PyYAML
        run: pip install PyYAML

      - name: Install oyaml
        run: pip install oyaml

      - name: Install prettytable
        run: pip install PrettyTable

      - name: Run Python script
        run: python yaml_to_table.py 

      - name: Update README
        run: |
          sed -i '/## Supported Currencies/, /## References/ { /## Supported Currencies/,/## References/!d }' README.md
          git add README.md
          git commit -m "Update README"{ /## Supported Currencies/,/## References/!d }'
          git push https://${{ secrets.GH_SECTER }}@github.com/polina-tereschenko/tableForCurrencies.git